// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package schema

import (
	"time"
)

type Session struct {
	ID        string    `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	Error     string    `json:"error"`
}

type Todo struct {
	ID          string `json:"id"`
	SessionID   string `json:"sessionId"`
	Description string `json:"description"`
	Checked     int64  `json:"checked"`
}
