// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package schema

import (
	"context"
)

const addSessionWithId = `-- name: AddSessionWithId :exec
insert into sessions(id, created_at, updated_at) values (?1, datetime(), datetime())
`

func (q *Queries) AddSessionWithId(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, addSessionWithId, id)
	return err
}

const addTodoWithIdAndSessionId = `-- name: AddTodoWithIdAndSessionId :exec
insert into todos(id, session_id, description, checked) values(?1, ?2, ?3, ?4)
`

type AddTodoWithIdAndSessionIdParams struct {
	ID          string `json:"id"`
	SessionID   string `json:"sessionId"`
	Description string `json:"description"`
	Checked     int64  `json:"checked"`
}

func (q *Queries) AddTodoWithIdAndSessionId(ctx context.Context, arg AddTodoWithIdAndSessionIdParams) error {
	_, err := q.db.ExecContext(ctx, addTodoWithIdAndSessionId,
		arg.ID,
		arg.SessionID,
		arg.Description,
		arg.Checked,
	)
	return err
}

const findSessionById = `-- name: FindSessionById :one
select id, created_at, updated_at, error from sessions where id = ?1
`

func (q *Queries) FindSessionById(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, findSessionById, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Error,
	)
	return i, err
}

const findTodosBySessionId = `-- name: FindTodosBySessionId :many
select id, session_id, description, checked from todos where session_id = ?1
`

func (q *Queries) FindTodosBySessionId(ctx context.Context, sessionID string) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, findTodosBySessionId, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Description,
			&i.Checked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const modifySessionById = `-- name: ModifySessionById :exec
update sessions set error = ?1 where id = ?2
`

type ModifySessionByIdParams struct {
	Error string `json:"error"`
	ID    string `json:"id"`
}

func (q *Queries) ModifySessionById(ctx context.Context, arg ModifySessionByIdParams) error {
	_, err := q.db.ExecContext(ctx, modifySessionById, arg.Error, arg.ID)
	return err
}

const removeTodosByIdAndSessionId = `-- name: RemoveTodosByIdAndSessionId :exec
delete from todos where id = ?1 and session_id = ?2
`

type RemoveTodosByIdAndSessionIdParams struct {
	ID        string `json:"id"`
	SessionID string `json:"sessionId"`
}

func (q *Queries) RemoveTodosByIdAndSessionId(ctx context.Context, arg RemoveTodosByIdAndSessionIdParams) error {
	_, err := q.db.ExecContext(ctx, removeTodosByIdAndSessionId, arg.ID, arg.SessionID)
	return err
}

const toggleTodosByIdAndSessionId = `-- name: ToggleTodosByIdAndSessionId :exec
update todos set checked = ?1 where id = ?2 and session_id = ?3
`

type ToggleTodosByIdAndSessionIdParams struct {
	Checked   int64  `json:"checked"`
	ID        string `json:"id"`
	SessionID string `json:"sessionId"`
}

func (q *Queries) ToggleTodosByIdAndSessionId(ctx context.Context, arg ToggleTodosByIdAndSessionIdParams) error {
	_, err := q.db.ExecContext(ctx, toggleTodosByIdAndSessionId, arg.Checked, arg.ID, arg.SessionID)
	return err
}
